
# Automatically updated by generate_winget_manifest.ts
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Geoxor.Amethyst
PackageVersion: 2.0.0-beta
PackageLocale: en-US
Publisher: Geoxor
PackageName: Amethyst
License: MIT
Copyright: Copyright © 2024 Geoxor
ShortDescription: A music player made with the web platform.
ManifestType: defaultLocale
ManifestVersion: 1.1.0
