
# Automatically updated by generate_winget_manifest.ts
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Geoxor.Amethyst
PackageVersion: 1.8.50
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://github.com/Geoxor/Amethyst/releases/download/v1.8.50/Amethyst-Setup-1.8.50.exe
  InstallerSha256: 7F973E9B821B772C6DF0362C5DB37899E556823BDB1ACB7CBF1F42868159AD26
- Architecture: x32
  InstallerType: nullsoft
  InstallerUrl: https://github.com/Geoxor/Amethyst/releases/download/v1.8.50/Amethyst-Setup-1.8.50.exe
  InstallerSha256: 7F973E9B821B772C6DF0362C5DB37899E556823BDB1ACB7CBF1F42868159AD26
ManifestType: installer
ManifestVersion: 1.1.0
