
# Automatically updated by generate_winget_manifest.ts
# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Geoxor.Amethyst
PackageVersion: 2.1.5
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0
