<template>
  <svg
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="currentColor"
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:svg="http://www.w3.org/2000/svg"
  >
    <rect
      id="rect1"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="4"
      ry="0.5"
    />
    <rect
      id="rect2"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="6"
      ry="0.5"
    />
    <rect
      id="rect3"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="8"
      ry="0.5"
    />
    <rect
      id="rect4"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="10"
      ry="0.5"
    />
    <rect
      id="rect5"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="12"
      ry="0.5"
    />
    <rect
      id="rect6"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="14"
      ry="0.5"
    />
    <rect
      id="rect7"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="16"
      ry="0.5"
    />
    <rect
      id="rect8"
      style="fill:currentColor;fill-opacity:1;paint-order:normal"
      width="8"
      height="1"
      x="8"
      y="18"
      ry="0.5"
    />
    <path
      id="path1"
      style="fill-opacity:0;stroke:currentColor;stroke-width:0.5;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacity:1;paint-order:normal"
      d="M 7.5,18.5 C 3.5,18.5 2,16 2,11 2,6 4,4.5 6,4.5 V 3 L 7.5,4.5 6,6 V 4.5"
    />
  </svg>
</template>