<script setup lang="ts">
import { FFT_SIZES } from "@shared/constants.js";

import { amethyst } from "@/amethyst.js";
import SettingsSetting from "@/components/settings/SettingsSetting.vue";
import DropdownInput from "@/components/v2/DropdownInput.vue";
import SliderInput from "@/components/v2/SliderInput.vue";
import ToggleSwitch from "@/components/v2/ToggleSwitch.vue";
import { SPECTRUM_TYPES } from "@/logic/settings.js";
const {metering} = amethyst.state.settings;
</script>

<template>
  <settings-setting
    :title="$t('settings.decibel_meter.title')"
    icon="ic:twotone-speed"
    :description="$t('settings.decibel_meter.description')"
  >
    <toggle-switch v-model="metering.decibelMeter.show" />
    <template
      v-if="metering.decibelMeter.show" 
      #subsettings
    >
      <div class="p-2 flex flex-col gap-2">
        <settings-setting
          subsetting
          :title="$t('settings.decibel_meter.separate_pre_post.title')"
          :description="$t('settings.decibel_meter.separate_pre_post.description')"
          icon="ic:twotone-speed"
        >
          <toggle-switch
            v-model="metering.decibelMeter.separatePrePost"
          />
        </settings-setting>

        <settings-setting
          subsetting
          :title="$t('settings.decibel_meter.minimum_db.title')"
          :description="$t('settings.decibel_meter.minimum_db.description')"
          icon="ic:twotone-speed"
        >
          <slider-input
            v-model="metering.decibelMeter.minimumDb"
            :min="-90"
            :max="-6"
            :step="1"
            suffix="dB"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.fft_size.title')"
          :description="$t('settings.fft_size.description')"
          icon="ic:twotone-line-style"
        >
          <dropdown-input
            v-model="metering.decibelMeter.fftSize"
            :options="FFT_SIZES"
            suffix="smp"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.decibel_meter.smoothing_duration.title')"
          :description="$t('settings.decibel_meter.smoothing_duration.description')"
          icon="ic:twotone-access-time"
        >
          <slider-input
            v-model="metering.decibelMeter.smoothingDuration"
            :min="0"
            :max="300"
            :step="10"
            suffix="ms"
          />
        </settings-setting>
      </div>
    </template>
  </settings-setting>

  <settings-setting
    :title="$t('settings.loudness_meter.title')"
    icon="ic:twotone-waves"
    :description="$t('settings.loudness_meter.description')"
  >
    <toggle-switch v-model="metering.loudnessMeter.show" />
  </settings-setting>

  <settings-setting
    :title="$t('settings.vectorscope.title')"
    icon="ic:twotone-fiber-smart-record"
    info="https://amethyst.geoxor.moe/user-manual/visuals/vectorscope"
    :description="$t('settings.vectorscope.description')"
  >
    <toggle-switch v-model="metering.vectorscope.show" />
    <template
      v-if="metering.vectorscope.show"
      #subsettings 
    >
      <div class="p-2 flex flex-col gap-2">
        <settings-setting
          subsetting
          :title="$t('settings.vectorscope.lissajous.title')"
          :description="$t('settings.vectorscope.lissajous.description')"
          icon="ic:twotone-fitbit"
        >
          <toggle-switch
            v-model="metering.vectorscope.lissajous"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.line_thickness.title')"
          :description="$t('settings.line_thickness.description')"
          icon="ic:twotone-drive-file-rename-outline"
        >
          <slider-input
            v-model="metering.vectorscope.lineThickness"
            :min="0.1"
            :max="10"
            :step="0.1"
            suffix="px"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.fft_size.title')"
          :description="$t('settings.fft_size.description')"
          icon="ic:twotone-line-style"
        >
          <dropdown-input
            v-model="metering.vectorscope.fftSize"
            :options="FFT_SIZES"
            suffix="smp"
          />
        </settings-setting>
      </div>
    </template>
  </settings-setting>

  <settings-setting
    :title="$t('settings.spectrum_analyzer.title')"
    icon="ic:twotone-graphic-eq"
    info="https://amethyst.geoxor.moe/user-manual/visuals/spectrum-analyzer"
    :description="$t('settings.spectrum_analyzer.description')"
  >
    <toggle-switch v-model="metering.spectrum.show" />
    <dropdown-input
      v-model="metering.spectrum.type"
      :options="SPECTRUM_TYPES"
    />
    <template
      v-if="metering.spectrum.show" 
      #subsettings
    >
      <div
        v-if="metering.spectrum.type == 'line'"
        class="p-2 flex flex-col gap-2"
      >
        <settings-setting
          subsetting
          :title="$t('settings.smoothing_duration.title')"
          :description="$t('settings.smoothing_duration.description')"
          icon="ic:twotone-access-time"
        >
          <slider-input
            v-model="metering.spectrumLine.smoothing"
            :min="0"
            :max="1"
            :step="0.01"
            suffix="ms"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.fft_size.title')"
          :description="$t('settings.fft_size.description')"
          icon="ic:twotone-line-style"
        >
          <dropdown-input
            v-model="metering.spectrumLine.fftSize"
            :options="FFT_SIZES"
            suffix="smp"
          />
        </settings-setting>

        <settings-setting
          subsetting
          :title="$t('settings.max_decibels.title')"
          :description="$t('settings.max_decibels.description')"
          icon="ic:twotone-keyboard-double-arrow-up"
        >
          <slider-input
            v-model="metering.spectrumLine.maxDecibels"
            :min="-64"
            :max="32"
            :step="1"
            suffix="dB"
          />
        </settings-setting>

        <settings-setting
          subsetting
          :title="$t('settings.min_decibels.title')"
          :description="$t('settings.min_decibels.description')"
          icon="ic:twotone-keyboard-double-arrow-down"
        >
          <slider-input
            v-model="metering.spectrumLine.minDecibels"
            :min="-128"
            :max="-32"
            :step="1"
            suffix="dB"
          />
        </settings-setting>

        <settings-setting
          subsetting
          :title="$t('settings.spectrum_line_analyzer.line_thickness.title')"
          :description="$t('settings.spectrum_line_analyzer.line_thickness.description')"
          icon="ic:twotone-line-weight"
        >
          <slider-input
            v-model="metering.spectrumLine.lineThickness"
            :min="1"
            :max="5"
            :step="0.5"
            suffix="px"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.spectrum_line_analyzer.fill_opacity.title')"
          :description="$t('settings.spectrum_line_analyzer.fill_opacity.description')"
          icon="ic:twotone-opacity"
        >
          <slider-input
            v-model="metering.spectrumLine.fillOpacity"
            :min="0"
            :max="1"
            :step="0.05"
            suffix=""
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.spectrum_line_analyzer.opacity_falloff.title')"
          :description="$t('settings.spectrum_line_analyzer.opacity_falloff.description')"
          icon="ic:twotone-gradient"
        >
          <slider-input
            v-model="metering.spectrumLine.opacityFalloff"
            :min="0"
            :max="1"
            :step="0.05"
            suffix="edf"
          />
          <!-- EDF = Exponential Distance Falloff (had to put something into suffix I guess xD) -->
        </settings-setting>
      </div>
      <div
        v-else-if="metering.spectrum.type == 'spectrogram'"
        class="p-2 flex flex-col gap-2"
      >
        <settings-setting
          subsetting
          :title="$t('settings.smoothing_duration.title')"
          :description="$t('settings.smoothing_duration.description')"
          icon="ic:twotone-access-time"
        >
          <slider-input
            v-model="metering.spectrogram.smoothing"
            :min="0"
            :max="1"
            :step="0.01"
            suffix="ms"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.fft_size.title')"
          :description="$t('settings.fft_size.description')"
          icon="ic:twotone-line-style"
        >
          <dropdown-input
            v-model="metering.spectrogram.fftSize"
            :options="FFT_SIZES"
            suffix="smp"
          />
        </settings-setting>
      </div>
      <div
        v-else-if="metering.spectrum.type == 'bars'"
        class="p-2 flex flex-col gap-2"
      >
        <settings-setting
          subsetting
          :title="$t('settings.smoothing_duration.title')"
          :description="$t('settings.smoothing_duration.description')"
          icon="ic:twotone-access-time"
        >
          <slider-input
            v-model="metering.spectrumBars.smoothing"
            :min="0"
            :max="1"
            :step="0.01"
            suffix="ms"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.fft_size.title')"
          :description="$t('settings.fft_size.description')"
          icon="ic:twotone-line-style"
        >
          <dropdown-input
            v-model="metering.spectrumBars.fftSize"
            :options="FFT_SIZES"
            suffix="smp"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.spectrum_bars_analyzer.bars.title')"
          :description="$t('settings.spectrum_bars_analyzer.bars.description')"
          icon="ic:twotone-line-style"
        >
          <slider-input
            v-model="metering.spectrumBars.bars"
            :min="16"
            :max="128"
            :step="8"
            suffix=""
          />
        </settings-setting>
      </div>
    </template>
  </settings-setting>

  <settings-setting
    :title="$t('settings.oscilloscope_analyzer.title')"
    icon="mdi:sawtooth-wave"
    :description="$t('settings.oscilloscope_analyzer.description')"
  >
    <toggle-switch v-model="metering.oscilloscope.show" />
    <template
      v-if="metering.oscilloscope.show"
      #subsettings
    >
      <div class="p-2 flex flex-col gap-2">
        <settings-setting
          subsetting
          :title="$t('settings.smoothing_duration.title')"
          :description="$t('settings.smoothing_duration.description')"
          icon="ic:twotone-access-time"
        >
          <slider-input
            v-model="metering.oscilloscope.smoothing"
            :min="0"
            :max="1"
            :step="0.01"
            suffix="ms"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.line_thickness.title')"
          :description="$t('settings.line_thickness.description')"
          icon="ic:twotone-drive-file-rename-outline"
        >
          <slider-input
            v-model="metering.oscilloscope.lineThickness"
            :min="0.1"
            :max="10"
            :step="0.1"
            suffix="px"
          />
        </settings-setting>
        <settings-setting
          subsetting
          :title="$t('settings.fft_size.title')"
          :description="$t('settings.fft_size.description')"
          icon="ic:twotone-line-style"
        >
          <dropdown-input
            v-model="metering.oscilloscope.fftSize"
            :options="FFT_SIZES"
            suffix="smp"
          />
        </settings-setting>
      </div>
    </template>
  </settings-setting>
</template>