import "virtual:uno.css";
import "vue-virtual-scroller/dist/vue-virtual-scroller.css";

import { loadIcons } from "@iconify/vue";

// Preload icons to not lazy load them later
loadIcons([
  "ic:baseline-arrow-drop-up",
  "ic:baseline-arrow-drop-down",
  "mdi:flask",
  "ic:twotone-audio-file",
  "ic:twotone-colorize",
  "mdi:resistor-nodes",
  "ic:twotone-close",
  "ic:twotone-settings",
  "ic:twotone-input",
  "solar:volume-knob-broken",
  "ic:twotone-crop-16-9",
  "ic:twotone-image",
  "ic:twotone-text-snippet",
  "ic:twotone-document-scanner",
  "ic:twotone-insert-drive-file",
  "ic:twotone-open-in-new",
  "ic:twotone-circle",
  "ic:twotone-link-off",
  "ic:twotone-power-settings-new",
  "ic:twotone-restart-alt",
  "ic:twotone-delete",
  "ic:twotone-volume-up",
  "ic:twotone-question-mark",
  "ic:twotone-palette",
  "ic:twotone-area-chart",
  "ic:twotone-psychology",
  "ic:twotone-analytics",
  "ic:twotone-folder",
  "ic:twotone-keyboard",
  "ic:twotone-data-saver-off",
  "ic:twotone-settings-applications",
  "ic:round-chevron-left",
  "line-md:loading-twotone-loop",
  "ic:twotone-keyboard-double-arrow-down",
  "mdi:information-slab-box-outline",
  "ic:round-volume-up",
  "ic:round-volume-off",
  "material-symbols:tag-rounded",
  "mdi:disc",
  "line-md:play-filled",
  "line-md:pause",
  "ic:baseline-drag-handle",
  "ic:twotone-error",
  "ic:baseline-folder-open",
  "ic:baseline-favorite-border",
  "ic:twotone-queue-music",
  "mdi:compass",
  "ic:twotone-mic-external-on",
  "ic:twotone-bug-report",
  "ic:round-favorite",
  "ic:twotone-favorite",
  "ic:round-shuffle",
  "ic:round-skip-next",
  "ic:round-pause",
  "ic:round-play-arrow",
  "ic:round-repeat",
  "ic:round-repeat-one",
  "ic:round-playlist-add",
  "ic:twotone-delete-sweep",
  "ic:twotone-refresh",
  "ic:twotone-control-point-duplicate",
  "ic:twotone-update",
  "mdi:dice-5",
  "ic:twotone-control-point-duplicate",
  "ic:twotone-favorite",
  "ic:twotone-list",
  "ic:twotone-plus",
  "ic:twotone-zoom-in",
  "ic:twotone-zoom-out",
  "ic:twotone-zoom-in-map",
  "ic:twotone-book",
  "ic:twotone-menu-book",
  "mdi:github",
  "ic:baseline-discord",
  "ic:twotone-access-time",
  "ic:twotone-format-bold",
  "ic:twotone-brush",
  "ic:twotone-plus",
  "ic:twotone-view-list",
  "ic:twotone-photo-size-select-actual",
  "ic:twotone-snippet-folder",
  "ic:twotone-fiber-smart-record",
  "ic:twotone-gradient",
  "ic:twotone-graphic-eq",
  "ic:twotone-keyboard-double-arrow-up",
  "ic:twotone-line-style",
  "ic:twotone-line-weight",
  "ic:twotone-speed",
  "ic:twotone-waves",
  "ic:twotone-pause",
  "ic:twotone-monitor-heart",
  "ic:twotone-discord",
  "ic:twotone-water-drop",
  "ic:twotone-rotate-90-degrees-ccw",
  "ic:twotone-opacity",
  "ic:twotone-blur-linear",
  "ic:twotone-auto-awesome",
  "ic:twotone-remove-red-eye",
  "ic:twotone-skip-next",
  "ic:twotone-format-strikethrough",
  "ic:twotone-rocket-launch",
  "ic:twotone-language",
  "ic:twotone-file-upload",
  "ic:twotone-file-download",
  "mdi:abacus",
  "mdi:audio-input-xlr",
  "mdi:audio-video",
  "material-symbols:memory-alt-rounded",
  "mdi:play",
]);

import "@/amethyst.js";

import { createApp } from "vue";
// @ts-ignore no types
import { RecycleScroller } from "vue-virtual-scroller";

import { i18n } from "@/amethyst.js";
import App from "@/App.vue";
import { router } from "@/router.js";

const app = createApp(App);

app.component("RecycleScroller", RecycleScroller);
app.use(i18n);
app.use(router);
app.mount("#app");
