require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/ios'
  pod 'CapacitorActionSheet', :path => '../../../node_modules/@capacitor/action-sheet'
  pod 'CapacitorDevice', :path => '../../../node_modules/@capacitor/device'
  pod 'CapacitorDialog', :path => '../../../node_modules/@capacitor/dialog'
  pod 'CapacitorFilesystem', :path => '../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../node_modules/@capacitor/haptics'
  pod 'CapacitorLocalNotifications', :path => '../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorSplashScreen', :path => '../../../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../../node_modules/@capacitor/status-bar'
  pod 'CapawesomeTeamCapacitorFileOpener', :path => '../../../node_modules/@capawesome-team/capacitor-file-opener'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../../node_modules/@capawesome/capacitor-file-picker'
  pod 'HugotomaziCapacitorNavigationBar', :path => '../../../node_modules/@hugotomazi/capacitor-navigation-bar'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
