// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IFluencyMaximize: typeof import('~icons/fluency/maximize')['default']
    IFluencyMinimize: typeof import('~icons/fluency/minimize')['default']
    IFluencyPause: typeof import('~icons/fluency/pause')['default']
    IFluencyPlay: typeof import('~icons/fluency/play')['default']
    IFluencyX: typeof import('~icons/fluency/x')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
